// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/jwtAuthpb/jwtAuthpb.proto

package jwtauthpb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Jwt struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jwt) Reset()         { *m = Jwt{} }
func (m *Jwt) String() string { return proto.CompactTextString(m) }
func (*Jwt) ProtoMessage()    {}
func (*Jwt) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea7db19593abeab5, []int{0}
}

func (m *Jwt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jwt.Unmarshal(m, b)
}
func (m *Jwt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jwt.Marshal(b, m, deterministic)
}
func (m *Jwt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jwt.Merge(m, src)
}
func (m *Jwt) XXX_Size() int {
	return xxx_messageInfo_Jwt.Size(m)
}
func (m *Jwt) XXX_DiscardUnknown() {
	xxx_messageInfo_Jwt.DiscardUnknown(m)
}

var xxx_messageInfo_Jwt proto.InternalMessageInfo

func (m *Jwt) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type JwtCheckResult struct {
	//jwt
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JwtCheckResult) Reset()         { *m = JwtCheckResult{} }
func (m *JwtCheckResult) String() string { return proto.CompactTextString(m) }
func (*JwtCheckResult) ProtoMessage()    {}
func (*JwtCheckResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea7db19593abeab5, []int{1}
}

func (m *JwtCheckResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtCheckResult.Unmarshal(m, b)
}
func (m *JwtCheckResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtCheckResult.Marshal(b, m, deterministic)
}
func (m *JwtCheckResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtCheckResult.Merge(m, src)
}
func (m *JwtCheckResult) XXX_Size() int {
	return xxx_messageInfo_JwtCheckResult.Size(m)
}
func (m *JwtCheckResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtCheckResult.DiscardUnknown(m)
}

var xxx_messageInfo_JwtCheckResult proto.InternalMessageInfo

func (m *JwtCheckResult) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *JwtCheckResult) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AuthCheckResult struct {
	//jwt
	User  string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	//jwt register certification
	Register             bool     `protobuf:"varint,3,opt,name=register,proto3" json:"register,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthCheckResult) Reset()         { *m = AuthCheckResult{} }
func (m *AuthCheckResult) String() string { return proto.CompactTextString(m) }
func (*AuthCheckResult) ProtoMessage()    {}
func (*AuthCheckResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea7db19593abeab5, []int{2}
}

func (m *AuthCheckResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthCheckResult.Unmarshal(m, b)
}
func (m *AuthCheckResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthCheckResult.Marshal(b, m, deterministic)
}
func (m *AuthCheckResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthCheckResult.Merge(m, src)
}
func (m *AuthCheckResult) XXX_Size() int {
	return xxx_messageInfo_AuthCheckResult.Size(m)
}
func (m *AuthCheckResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthCheckResult.DiscardUnknown(m)
}

var xxx_messageInfo_AuthCheckResult proto.InternalMessageInfo

func (m *AuthCheckResult) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *AuthCheckResult) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthCheckResult) GetRegister() bool {
	if m != nil {
		return m.Register
	}
	return false
}

type JwtRequest struct {
	JwtRequest           *Jwt     `protobuf:"bytes,1,opt,name=jwt_request,json=jwtRequest,proto3" json:"jwt_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JwtRequest) Reset()         { *m = JwtRequest{} }
func (m *JwtRequest) String() string { return proto.CompactTextString(m) }
func (*JwtRequest) ProtoMessage()    {}
func (*JwtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea7db19593abeab5, []int{3}
}

func (m *JwtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtRequest.Unmarshal(m, b)
}
func (m *JwtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtRequest.Marshal(b, m, deterministic)
}
func (m *JwtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtRequest.Merge(m, src)
}
func (m *JwtRequest) XXX_Size() int {
	return xxx_messageInfo_JwtRequest.Size(m)
}
func (m *JwtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JwtRequest proto.InternalMessageInfo

func (m *JwtRequest) GetJwtRequest() *Jwt {
	if m != nil {
		return m.JwtRequest
	}
	return nil
}

type JwtResponse struct {
	JwtCheckResult       *JwtCheckResult `protobuf:"bytes,1,opt,name=jwt_check_result,json=jwtCheckResult,proto3" json:"jwt_check_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JwtResponse) Reset()         { *m = JwtResponse{} }
func (m *JwtResponse) String() string { return proto.CompactTextString(m) }
func (*JwtResponse) ProtoMessage()    {}
func (*JwtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea7db19593abeab5, []int{4}
}

func (m *JwtResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtResponse.Unmarshal(m, b)
}
func (m *JwtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtResponse.Marshal(b, m, deterministic)
}
func (m *JwtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtResponse.Merge(m, src)
}
func (m *JwtResponse) XXX_Size() int {
	return xxx_messageInfo_JwtResponse.Size(m)
}
func (m *JwtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JwtResponse proto.InternalMessageInfo

func (m *JwtResponse) GetJwtCheckResult() *JwtCheckResult {
	if m != nil {
		return m.JwtCheckResult
	}
	return nil
}

type AuthResponse struct {
	AuthCheckResult      *AuthCheckResult `protobuf:"bytes,1,opt,name=auth_check_result,json=authCheckResult,proto3" json:"auth_check_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea7db19593abeab5, []int{5}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetAuthCheckResult() *AuthCheckResult {
	if m != nil {
		return m.AuthCheckResult
	}
	return nil
}

func init() {
	proto.RegisterType((*Jwt)(nil), "jwtauth.Jwt")
	proto.RegisterType((*JwtCheckResult)(nil), "jwtauth.JwtCheckResult")
	proto.RegisterType((*AuthCheckResult)(nil), "jwtauth.AuthCheckResult")
	proto.RegisterType((*JwtRequest)(nil), "jwtauth.JwtRequest")
	proto.RegisterType((*JwtResponse)(nil), "jwtauth.JwtResponse")
	proto.RegisterType((*AuthResponse)(nil), "jwtauth.AuthResponse")
}

func init() { proto.RegisterFile("src/jwtAuthpb/jwtAuthpb.proto", fileDescriptor_ea7db19593abeab5) }

var fileDescriptor_ea7db19593abeab5 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x34, 0xd6, 0x8f, 0xe6, 0xa5, 0xb4, 0x75, 0xad, 0x34, 0x14, 0x84, 0xb2, 0xa7, 0x5e, 0x8c,
	0x50, 0x0f, 0xa2, 0x9e, 0xaa, 0x9e, 0x72, 0x92, 0x55, 0x10, 0xbc, 0x94, 0x24, 0x2c, 0x26, 0x6b,
	0x35, 0x71, 0xf7, 0xc5, 0xbd, 0xfa, 0xd3, 0x65, 0x37, 0x31, 0x6d, 0xa4, 0x27, 0x6f, 0x6f, 0x5e,
	0x66, 0xe6, 0xcd, 0x84, 0x85, 0x53, 0x25, 0x93, 0x73, 0xa1, 0x71, 0x51, 0x62, 0x5a, 0xc4, 0xeb,
	0x29, 0x28, 0x64, 0x8e, 0x39, 0x39, 0x14, 0x1a, 0xa3, 0x12, 0x53, 0x3a, 0x86, 0x4e, 0xa8, 0x91,
	0x0c, 0xa1, 0x23, 0x34, 0xfa, 0xce, 0xd4, 0x99, 0xb9, 0xcc, 0x8c, 0xf4, 0x1a, 0xfa, 0xa1, 0xc6,
	0xbb, 0x94, 0x27, 0x6f, 0x8c, 0xab, 0x72, 0x85, 0x84, 0xc0, 0x5e, 0xa9, 0xb8, 0xac, 0x49, 0x76,
	0x26, 0x23, 0xd8, 0xe7, 0xef, 0x51, 0xb6, 0xf2, 0x77, 0xed, 0xb2, 0x02, 0xf4, 0x19, 0x06, 0xe6,
	0xda, 0xbf, 0xc4, 0x64, 0x02, 0x5d, 0xc9, 0x5f, 0x33, 0x85, 0x5c, 0xfa, 0x9d, 0xa9, 0x33, 0xeb,
	0xb2, 0x06, 0xd3, 0x1b, 0x80, 0x50, 0x23, 0xe3, 0x9f, 0x25, 0x57, 0x48, 0xce, 0xc0, 0x13, 0x1a,
	0x97, 0xb2, 0x82, 0xd6, 0xda, 0x9b, 0xf7, 0x82, 0xba, 0x5a, 0x60, 0x98, 0x20, 0x1a, 0x3a, 0x7d,
	0x00, 0xcf, 0x8a, 0x55, 0x91, 0x7f, 0x28, 0x4e, 0x16, 0x30, 0x34, 0xea, 0xc4, 0x84, 0x5c, 0x4a,
	0x9b, 0xb2, 0xb6, 0x18, 0x6f, 0x5a, 0x6c, 0x94, 0x60, 0x7d, 0xd1, 0xc2, 0xf4, 0x09, 0x7a, 0xa6,
	0x67, 0x63, 0x79, 0x0f, 0x47, 0x46, 0xb6, 0xcd, 0xd3, 0x6f, 0x3c, 0xff, 0xfc, 0x19, 0x36, 0x88,
	0xda, 0x8b, 0xf9, 0xb7, 0x63, 0x5b, 0x3e, 0x72, 0xf9, 0x95, 0x25, 0x9c, 0x5c, 0x42, 0xf7, 0x37,
	0x06, 0x39, 0x6e, 0x95, 0xab, 0x7a, 0x4d, 0x46, 0xed, 0x65, 0x95, 0x85, 0xee, 0x90, 0x2b, 0x70,
	0x9b, 0x5b, 0xdb, 0x95, 0x27, 0xad, 0x50, 0x6b, 0xe9, 0xad, 0xf7, 0xe2, 0xd6, 0x5f, 0x8a, 0x38,
	0x3e, 0xb0, 0x4f, 0xe6, 0xe2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x31, 0x94, 0x5b, 0x7c, 0x53, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JwtServiceClient is the client API for JwtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JwtServiceClient interface {
	//jwt
	JwtCheck(ctx context.Context, in *JwtRequest, opts ...grpc.CallOption) (*JwtResponse, error)
	//Auth
	AuthCheck(ctx context.Context, in *JwtRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type jwtServiceClient struct {
	cc *grpc.ClientConn
}

func NewJwtServiceClient(cc *grpc.ClientConn) JwtServiceClient {
	return &jwtServiceClient{cc}
}

func (c *jwtServiceClient) JwtCheck(ctx context.Context, in *JwtRequest, opts ...grpc.CallOption) (*JwtResponse, error) {
	out := new(JwtResponse)
	err := c.cc.Invoke(ctx, "/jwtauth.JwtService/JwtCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jwtServiceClient) AuthCheck(ctx context.Context, in *JwtRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/jwtauth.JwtService/AuthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JwtServiceServer is the server API for JwtService service.
type JwtServiceServer interface {
	//jwt
	JwtCheck(context.Context, *JwtRequest) (*JwtResponse, error)
	//Auth
	AuthCheck(context.Context, *JwtRequest) (*AuthResponse, error)
}

// UnimplementedJwtServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJwtServiceServer struct {
}

func (*UnimplementedJwtServiceServer) JwtCheck(ctx context.Context, req *JwtRequest) (*JwtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JwtCheck not implemented")
}
func (*UnimplementedJwtServiceServer) AuthCheck(ctx context.Context, req *JwtRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthCheck not implemented")
}

func RegisterJwtServiceServer(s *grpc.Server, srv JwtServiceServer) {
	s.RegisterService(&_JwtService_serviceDesc, srv)
}

func _JwtService_JwtCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JwtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServiceServer).JwtCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwtauth.JwtService/JwtCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServiceServer).JwtCheck(ctx, req.(*JwtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JwtService_AuthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JwtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServiceServer).AuthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwtauth.JwtService/AuthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServiceServer).AuthCheck(ctx, req.(*JwtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JwtService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jwtauth.JwtService",
	HandlerType: (*JwtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JwtCheck",
			Handler:    _JwtService_JwtCheck_Handler,
		},
		{
			MethodName: "AuthCheck",
			Handler:    _JwtService_AuthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/jwtAuthpb/jwtAuthpb.proto",
}
